# brew bundle

# taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

# CL applications
brew "ack"
brew "autoconf"
brew "automake"
brew "openssl"
brew "python", link: false
brew "awscli"
brew "coreutils"
brew "direnv"
brew "git"
brew "httpie"
brew "jq"
brew "mas"
brew "neofetch"
brew "node"
brew "pipenv"
brew "pyenv"
brew "pyenv-virtualenv"
brew "telnet"
brew "thefuck"
brew "tmux"
brew "tree"
brew "wget"
brew "yarn"
brew "zlib"

# GUI applications
cask "1password"
cask "alfred"
cask "bartender"
cask "brave-browser"
cast "daisydisk"
cask "firefox-developer-edition"
cask "google-backup-and-sync"
cask "iterm2"
cask "osxfuse"
cask "paw"
cask "postico"
cask "spotify"
cask "sublime-merge"
cask "sublime-text"
cask "transmission"
cask "veracrypt"
cask "vlc"

# Mac App Store applications
mas "Affinity Designer", id: 824171161
mas "Fantastical", id: 975937182
mas "Magnet", id: 441258766
mas "Slack", id: 803453959
mas "Telegram", id: 747648890
mas "Textual IRC Client", id: 1262957439
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
