# zsh setup
export ZSH=$HOME/.oh-my-zsh


# plugins
# install highlighting: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
plugins=(
  git
  thefuck
  sublime
  zsh-syntax-highlighting
)
source $ZSH/oh-my-zsh.sh


# basic options
export CLICOLOR=1


# aliases
source ~/.aliases
source ~/.aliases-os


# functions
source ~/.functions


# paths
source ~/.paths


# prompt init
# install spaceship: npm install -g spaceship-prompt
autoload -U promptinit; promptinit
SPACESHIP_CHAR_SYMBOL="❯ "
SPACESHIP_VENV_SHOW=false
prompt spaceship


# the fuck?
eval $(thefuck --alias)


# direnv
eval "$(direnv hook zsh)"


# pyenv
export PATH="$HOME/.pyenv/bin:$PATH"
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"


# OpenSSL
export PATH="/usr/local/opt/openssl/bin:$PATH"
