# zsh
export ZSH="$HOME/.oh-my-zsh"

# plugins
plugins=(
  colored-man-pages
  git
  sublime
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# basic options
export CLICOLOR=1

# prompt
eval "$(starship init zsh)"


# aliases
source ~/.aliases
source ~/.aliases-os

# functions
source ~/.functions


# paths
source ~/.paths


# direnv
eval "$(direnv hook zsh)"


# pyenv
eval "$(pyenv init -)"
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi
export PYENV_VIRTUALENV_DISABLE_PROMPT=1


# OpenSSL
export PATH="/usr/local/opt/openssl/bin:$PATH"


# Additional Custom Configs
unsetopt nomatch
foreach file (`echo ~/.zshrc-*`)
    if [[ -a $file ]]; then
        source $file
    fi
end
setopt nomatch

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"



export PATH="$HOME/.poetry/bin:$PATH"
